id: A01D7A71D
base_file: fC074.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-05 20:15:15.089025
  last_modified_at: 2022-06-05 20:15:15.089032
